version: '3.8'

services:
  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_URL=mongodb://localhost:27017/levita-backend-test
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017
