imports:

  - { resource: ./apps/user.yaml }
  - { resource: ./Users/application.yaml }


  - { resource: ./apps/game.yaml }
  - { resource: ./Games/application.yaml }

  - { resource: ./apps/wordPicker.yaml }
  - { resource: ./WordPickers/application.yaml }
