imports:
  - { resource: ./application.yaml }

services:
  Levita.EnvironmentArranger:
    class: ../../../../../tests/contexts/shared/infrastructure/typeorm/TypeOrmEnvironmentArranger
    arguments: ['@Levita.ConnectionManager']
